In [39]:
using LinearAlgebra, Latexify

In [8]:
A = zeros(Int, 3, 3)
while true
  A = rand(-5:5, 3, 3)
  abs(det(A)) == 4 && break
end
A

3×3 Matrix{Int64}:
 1   5  -2
 0  -4   3
 4   4   5

In [10]:
norm(A[:,1])

4.123105625617661

In [11]:
A[:,1]/norm(A[:,1])

3-element Vector{Float64}:
 0.24253562503633297
 0.0
 0.9701425001453319

In [27]:
S = [0 -1 2
1 0 1
-2 -1 0]

3×3 Matrix{Int64}:
  0  -1  2
  1   0  1
 -2  -1  0

In [28]:
Q = rationalize.((I-S)*inv(I+S), tol = 10e-3)

3×3 Matrix{Rational{Int64}}:
 -3//7  -2//7  -6//7
 -6//7   3//7   2//7
  2//7   6//7  -3//7

In [31]:
R = 7*[3 -2 5
0 1 4
0 0 -5]

3×3 Matrix{Int64}:
 21  -14   35
  0    7   28
  0    0  -35

In [35]:
A = Q*R

3×3 Matrix{Rational{Int64}}:
  -9   4    7
 -18  15  -28
   6   2   49

In [40]:
latexify(A)

L"\begin{equation}
\left[
\begin{array}{ccc}
-9 & 4 & 7 \\
-18 & 15 & -28 \\
6 & 2 & 49 \\
\end{array}
\right]
\end{equation}
"

In [36]:
norm(A[:,1])

21.0

In [42]:
q1 = A[:,1]// 21

3-element Vector{Rational{Int64}}:
 -3//7
 -6//7
  2//7

In [48]:
q1'*A[:,2] *q1

3-element Vector{Rational{Int64}}:
  6
 12
 -4

In [43]:
u2 = A[:,2] - q1'*A[:,2] * q1

3-element Vector{Rational{Int64}}:
 -2
  3
  6

In [44]:
norm(u2)

7.0

In [46]:
q2 = u2 // 7

3-element Vector{Rational{Int64}}:
 -2//7
  3//7
  6//7

In [49]:
q2'*A[:,3]

28//1

In [50]:
q1'*A[:,3]

35//1

In [53]:
u3 = A[:,3] - 28*q2 - 35*q1

3-element Vector{Rational{Int64}}:
  30
 -10
  15

In [54]:
norm(u3)

35.0

In [55]:
q3 = u3//35

3-element Vector{Rational{Int64}}:
  6//7
 -2//7
  3//7

In [56]:
q1

3-element Vector{Rational{Int64}}:
 -3//7
 -6//7
  2//7

In [57]:
Q = [q1 q2 q3]

3×3 Matrix{Rational{Int64}}:
 -3//7  -2//7   6//7
 -6//7   3//7  -2//7
  2//7   6//7   3//7

In [58]:
Q'*A

3×3 Matrix{Rational{Int64}}:
 21  -14  35
  0    7  28
  0    0  35

In [59]:
latexify(Q'*A)

L"\begin{equation}
\left[
\begin{array}{ccc}
21 & -14 & 35 \\
0 & 7 & 28 \\
0 & 0 & 35 \\
\end{array}
\right]
\end{equation}
"

In [60]:
A = [
  3 -2 1
  6 0 4
  -6 -8 -7
]

3×3 Matrix{Int64}:
  3  -2   1
  6   0   4
 -6  -8  -7

In [61]:
norm(A[:,1])

9.0

In [63]:
q1 = A[:,1]//9

3-element Vector{Rational{Int64}}:
  1//3
  2//3
 -2//3

In [73]:
a2 = A[:,2] - A[:,2]'*q1*q1

3-element Vector{Rational{Int64}}:
 -32//9
 -28//9
 -44//9

In [80]:
9*norm(a2)^2/16

26.0

In [72]:
q2 = a2 //(11//3)

3-element Vector{Rational{Int64}}:
 -1//3
 -2//3
  2//3

In [82]:
a21 = a2*9//4

3-element Vector{Rational{Int64}}:
  -8
  -7
 -11

In [83]:
a21[1]^2+a21[2]^2+a21[3]^2

234//1

In [84]:
q2 = a21/sqrt(234)

3-element Vector{Float64}:
 -0.5229763603684907
 -0.4576043153224294
 -0.7190924955066748

In [88]:
a3 = A[:,3] - q2'*A[:,3]*q2 - q1'*A[:,3]*q1

3-element Vector{Float64}:
 -0.15384615384615374
  0.11538461538461586
  0.038461538461538325

In [91]:
q3 = a3/norm(a3)

3-element Vector{Float64}:
 -0.784464540552735
  0.5883484054145541
  0.19611613513818318

In [92]:
Q = [q1 q2 q3]

3×3 Matrix{Float64}:
  0.333333  -0.522976  -0.784465
  0.666667  -0.457604   0.588348
 -0.666667  -0.719092   0.196116

In [100]:
-Q'*A

3×3 Matrix{Float64}:
 -9.0          -4.66667      -7.66667
  2.22045e-16  -6.79869      -2.68025
 -2.07057e-14  -4.44089e-15  -0.196116

In [97]:
QR = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -9.0  -4.66667  -7.66667
  0.0   6.79869   2.68025
  0.0   0.0      -0.196116

In [99]:
Matrix(QR.Q)

3×3 Matrix{Float64}:
 -0.333333  -0.522976   0.784465
 -0.666667  -0.457604  -0.588348
  0.666667  -0.719092  -0.196116

In [101]:
QR.R

3×3 Matrix{Float64}:
 -9.0  -4.66667  -7.66667
  0.0   6.79869   2.68025
  0.0   0.0      -0.196116

In [106]:
QR.R \ (QR.Q'*[14; 22; -9])

3-element Vector{Float64}:
  2.999999999999997
 -2.000000000000001
  1.0000000000000033