In [1]:
using LinearAlgebra, Latexify

In [2]:
A = zeros(Int, 3, 3)
while true
  A = rand(-5:5, 3, 3)
  abs(det(A)) == 4 && break
end
A

3×3 Matrix{Int64}:
 -3  -2   1
 -4  -2   2
  3  -3  -4

In [3]:
norm(A[:,1])

5.830951894845301

In [4]:
A[:,1]/norm(A[:,1])

3-element Vector{Float64}:
 -0.5144957554275265
 -0.6859943405700353
  0.5144957554275265

In [5]:
S = [0 -1 2
1 0 1
-2 -1 0]

3×3 Matrix{Int64}:
  0  -1  2
  1   0  1
 -2  -1  0

In [6]:
Q = rationalize.((I-S)*inv(I+S), tol = 10e-3)

3×3 Matrix{Rational{Int64}}:
 -3//7  -2//7  -6//7
 -6//7   3//7   2//7
  2//7   6//7  -3//7

In [7]:
R = 7*[3 -2 5
0 1 4
0 0 -5]

3×3 Matrix{Int64}:
 21  -14   35
  0    7   28
  0    0  -35

In [8]:
A = Q*R

3×3 Matrix{Rational{Int64}}:
  -9   4    7
 -18  15  -28
   6   2   49

In [9]:
latexify(A)

L"\begin{equation}
\left[
\begin{array}{ccc}
-9 & 4 & 7 \\
-18 & 15 & -28 \\
6 & 2 & 49 \\
\end{array}
\right]
\end{equation}
"

In [10]:
norm(A[:,1])

21.0

In [11]:
q1 = A[:,1]// 21

3-element Vector{Rational{Int64}}:
 -3//7
 -6//7
  2//7

In [12]:
q1'*A[:,2] *q1

3-element Vector{Rational{Int64}}:
  6
 12
 -4

In [13]:
u2 = A[:,2] - q1'*A[:,2] * q1

3-element Vector{Rational{Int64}}:
 -2
  3
  6

In [14]:
norm(u2)

7.0

In [15]:
q2 = u2 // 7

3-element Vector{Rational{Int64}}:
 -2//7
  3//7
  6//7

In [16]:
q2'*A[:,3]

28//1

In [17]:
q1'*A[:,3]

35//1

In [18]:
u3 = A[:,3] - 28*q2 - 35*q1

3-element Vector{Rational{Int64}}:
  30
 -10
  15

In [19]:
norm(u3)

35.0

In [20]:
q3 = u3//35

3-element Vector{Rational{Int64}}:
  6//7
 -2//7
  3//7

In [21]:
q1

3-element Vector{Rational{Int64}}:
 -3//7
 -6//7
  2//7

In [22]:
Q = [q1 q2 q3]

3×3 Matrix{Rational{Int64}}:
 -3//7  -2//7   6//7
 -6//7   3//7  -2//7
  2//7   6//7   3//7

In [23]:
Q'*A

3×3 Matrix{Rational{Int64}}:
 21  -14  35
  0    7  28
  0    0  35

In [24]:
latexify(Q'*A)

L"\begin{equation}
\left[
\begin{array}{ccc}
21 & -14 & 35 \\
0 & 7 & 28 \\
0 & 0 & 35 \\
\end{array}
\right]
\end{equation}
"

In [25]:
A = [
  3 -2 1
  6 0 4
  -6 -8 -7
]

3×3 Matrix{Int64}:
  3  -2   1
  6   0   4
 -6  -8  -7

In [26]:
norm(A[:,1])

9.0

In [27]:
q1 = A[:,1]//9

3-element Vector{Rational{Int64}}:
  1//3
  2//3
 -2//3

In [28]:
a2 = A[:,2] - A[:,2]'*q1*q1

3-element Vector{Rational{Int64}}:
 -32//9
 -28//9
 -44//9

In [29]:
9*norm(a2)^2/16

26.0

In [30]:
q2 = a2 //(11//3)

3-element Vector{Rational{Int64}}:
 -32//33
 -28//33
  -4//3

In [31]:
a21 = a2*9//4

3-element Vector{Rational{Int64}}:
  -8
  -7
 -11

In [32]:
a21[1]^2+a21[2]^2+a21[3]^2

234//1

In [33]:
q2 = a21/sqrt(234)

3-element Vector{Float64}:
 -0.5229763603684907
 -0.4576043153224294
 -0.7190924955066748

In [34]:
a3 = A[:,3] - q2'*A[:,3]*q2 - q1'*A[:,3]*q1

3-element Vector{Float64}:
 -0.15384615384615374
  0.11538461538461586
  0.038461538461538325

In [35]:
q3 = a3/norm(a3)

3-element Vector{Float64}:
 -0.784464540552735
  0.5883484054145541
  0.19611613513818318

In [36]:
Q = [q1 q2 q3]

3×3 Matrix{Float64}:
  0.333333  -0.522976  -0.784465
  0.666667  -0.457604   0.588348
 -0.666667  -0.719092   0.196116

In [37]:
-Q'*A

3×3 Matrix{Float64}:
 -9.0          -4.66667      -7.66667
  2.22045e-16  -6.79869      -2.68025
 -2.07057e-14  -4.44089e-15  -0.196116

In [38]:
QR = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -9.0  -4.66667  -7.66667
  0.0   6.79869   2.68025
  0.0   0.0      -0.196116

In [39]:
Matrix(QR.Q)

3×3 Matrix{Float64}:
 -0.333333  -0.522976   0.784465
 -0.666667  -0.457604  -0.588348
  0.666667  -0.719092  -0.196116

In [40]:
QR.R

3×3 Matrix{Float64}:
 -9.0  -4.66667  -7.66667
  0.0   6.79869   2.68025
  0.0   0.0      -0.196116

In [41]:
QR.R \ (QR.Q'*[14; 22; -9])

3-element Vector{Float64}:
  2.999999999999997
 -2.000000000000001
  1.0000000000000033

### Using QR to find eigenvalues

In [42]:
A = [1 0 0; 3 -2 6; 2 1 3]

3×3 Matrix{Int64}:
 1   0  0
 3  -2  6
 2   1  3

In [43]:
A₀ = A
QR₀ = qr(A₀)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -3.74166  1.06904  -6.41427
  0.0      1.96396  -1.09109
  0.0      0.0       1.63299

In [44]:
Matrix(QR₀.R)

3×3 Matrix{Float64}:
 -3.74166  1.06904  -6.41427
  0.0      1.96396  -1.09109
  0.0      0.0       1.63299

In [47]:
A₁ = QR₀.R * QR₀.Q

3×3 Matrix{Float64}:
  3.57143   -6.29869   1.96396
 -0.99146   -2.01587  -0.0296957
 -0.872872   1.30661   0.444444

In [48]:
QR₁ = qr(A₁)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -3.80789  5.6822   -1.74786
  0.0      3.62727  -0.495724
  0.0      0.0       0.868795

In [49]:
A₂ = QR₁.R * QR₁.Q

3×3 Matrix{Float64}:
 4.65025   -4.45991      -2.88562
 0.830799  -3.49591      -0.700881
 0.199152   0.000981054   0.845661

In [50]:
QR₂ = qr(A₂)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -4.72807  5.00074  2.92566
  0.0      2.66547  0.258938
  0.0      0.0      0.952189

In [51]:
A₃ = QR₂.R * QR₂.Q

3×3 Matrix{Float64}:
  3.6483     -5.49122    3.52957
 -0.479273   -2.59664    0.446711
 -0.0401072   0.0755963  0.948335

In [52]:
QR₃ = qr(A₃)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -3.67987  5.10675  -3.43078
  0.0      3.28981  -0.89664
  0.0      0.0       0.991239

In [53]:
A₄ = QR₃.R * QR₃.Q

3×3 Matrix{Float64}:
 4.27602    -4.60494     -3.44975
 0.418699   -3.26719     -0.881472
 0.0108036   0.00600724   0.991162

In [55]:
Aₖ = A
for i=1:25
  QRₖ = qr(Aₖ)
  Aₖ = QRₖ.R * QRₖ.Q
end
Aₖ

3×3 Matrix{Float64}:
  3.99934      -5.00092      3.53563
 -0.000921692  -2.99934      0.706641
 -2.34445e-15   1.27349e-12  1.0

In [56]:
A = zeros(Int,3,3)
while true
  A = rand(-5:5,3,3)
  abs(norm(A[:,1])-3) < 1e-3  && break
end
A

3×3 Matrix{Int64}:
 -1   1   3
  2   2  -2
  2  -1   5

In [57]:
qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 3.0   0.333333  1.0
 0.0  -2.4267    2.60985
 0.0   0.0       5.49442

In [59]:
A* [4;-2;0]

3-element Vector{Int64}:
 -6
  4
 10

In [60]:
A = rand(-4:4,4,4)

4×4 Matrix{Int64}:
  4   3  -1  0
 -1  -3   1  4
  2   0   2  4
  2  -1  -4  2