In [10]:
using LinearAlgebra

In [2]:
A = [ 1 2 3 4 5
-2 1 0 3 1
3 0 4 -2 1]

3×5 Matrix{Int64}:
  1  2  3   4  5
 -2  1  0   3  1
  3  0  4  -2  1

In [11]:
E1 = [1 0 0
2 1 0
0 0 1]

3×3 Matrix{Int64}:
 1  0  0
 2  1  0
 0  0  1

In [12]:
E1*A

3×5 Matrix{Int64}:
 1  2  3   4   5
 0  5  6  11  11
 3  0  4  -2   1

In [13]:
E2 = [1 0 0; 0 1 0; -3 0 01]

3×3 Matrix{Int64}:
  1  0  0
  0  1  0
 -3  0  1

In [14]:
E2*E1*A

3×5 Matrix{Int64}:
 1   2   3    4    5
 0   5   6   11   11
 0  -6  -5  -14  -14

In [15]:
A = [1 2 0; 0 -2 2; 3 0 1]

3×3 Matrix{Int64}:
 1   2  0
 0  -2  2
 3   0  1

In [16]:
E1 = [1 0 0; 0 1 0; -3 0 1]

3×3 Matrix{Int64}:
  1  0  0
  0  1  0
 -3  0  1

In [17]:
E1*A

3×3 Matrix{Int64}:
 1   2  0
 0  -2  2
 0  -6  1

In [18]:
E2 = [1 0 0; 0 1 0; 0 -3 1]
E2*E1*A

3×3 Matrix{Int64}:
 1   2   0
 0  -2   2
 0   0  -5

In [19]:
inv(E1)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 3.0  0.0  1.0

In [20]:
inv(E2)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  3.0  1.0

In [21]:
E3 = [1 1 0; 0 1 0; 0 0 1]

3×3 Matrix{Int64}:
 1  1  0
 0  1  0
 0  0  1

In [23]:
E3*E2*E1*A

3×3 Matrix{Int64}:
 1   0   2
 0  -2   2
 0   0  -5

In [24]:
inv(E3)

3×3 Matrix{Float64}:
 1.0  -1.0  0.0
 0.0   1.0  0.0
 0.0   0.0  1.0

In [25]:
E4 = [1 0 0; 0 1 0; 0 0 -1//5]
E4*E3*E2*E1*A

3×3 Matrix{Rational{Int64}}:
 1   0  2
 0  -2  2
 0   0  1

In [26]:
inv(E4)

3×3 Matrix{Rational{Int64}}:
 1  0   0
 0  1   0
 0  0  -5

In [29]:
E5 = [1 0 0; 0 1 -2; 0 0 1]
E5*E4*E3*E2*E1*A

3×3 Matrix{Rational{Int64}}:
 1   0  2
 0  -2  0
 0   0  1

In [30]:
E6 = [1 0 -2; 0 1 0; 0 0 1]
E6*E5*E4*E3*E2*E1*A

3×3 Matrix{Rational{Int64}}:
 1   0  0
 0  -2  0
 0   0  1

In [31]:
E7 = [1 0 0; 0 -1//2 0; 0 0 1]

3×3 Matrix{Rational{Int64}}:
 1    0    0
 0  -1//2  0
 0    0    1

In [32]:
E7*E6*E5*E4*E3*E2*E1*A

3×3 Matrix{Rational{Int64}}:
 1  0  0
 0  1  0
 0  0  1

In [33]:
inv(E1)*inv(E2)*inv(E3)*inv(E4)*inv(E5)*inv(E6)*inv(E7)

3×3 Matrix{Float64}:
 1.0   2.0  0.0
 0.0  -2.0  2.0
 3.0   0.0  1.0

In [40]:
A = [1 2 0 2
0 -2 1 2
1 3 0 1
0 1 -1 0]

4×4 Matrix{Int64}:
 1   2   0  2
 0  -2   1  2
 1   3   0  1
 0   1  -1  0

In [41]:
det(A)

-1.0

In [22]:
while true
A = rand(-4:4,3,3)
abs(det(A)) < 6 && break
end
A

3×3 Matrix{Int64}:
 -1   2  -1
  4   1  -1
  2  -2   1

In [30]:
det(A)

-1.0000000000000004

In [24]:
minor(A, i, j) = A[setdiff(1:size(A,1), i),setdiff(1:size(A,2),j)]
cofactor(A, i, j) = (-1)^(i+j) * det(minor(A,i,j))

cofactor (generic function with 1 method)

In [25]:
minor(A,1,2)

2×2 Matrix{Int64}:
 4  -1
 2   1

In [26]:
minor(A,3,3)

2×2 Matrix{Int64}:
 -1  2
  4  1

In [27]:
cofactor(A,1,2),cofactor(A,3,3)

(-6.0, -9.0)

In [34]:
C = zeros(Int, 3,3)
for i=1:3
  for j=1:3
    C[i,j] = round(Int, cofactor(A,i,j))
  end
end
C

3×3 Matrix{Int64}:
 -1  -6  -10
  0   1    2
 -1  -5   -9

In [29]:
C'*A

3×3 Matrix{Int64}:
 -1   0   0
  0  -1   0
  0   0  -1

In [16]:
det(A) * inv(A)'

3×3 Matrix{Float64}:
  -7.0           10.0  -11.0
 -28.0          -12.0   -5.0
  -1.85037e-16   13.0   13.0

In [17]:
det(A)

-91.0

In [18]:
inv(A)

3×3 Matrix{Float64}:
  0.0769231  0.307692    2.03338e-18
 -0.10989    0.131868   -0.142857
  0.120879   0.0549451  -0.142857

In [31]:
A

3×3 Matrix{Int64}:
 -1   2  -1
  4   1  -1
  2  -2   1

In [33]:
cofactor(A,1,2), cofactor(A,3,3)

(-6.0, -9.0)

In [36]:
A*C'

3×3 Matrix{Int64}:
 -1   0   0
  0  -1   0
  0   0  -1

In [41]:
while true
A = rand(-2:2,4,4)
abs(det(A)) == 0 && break
end
A

4×4 Matrix{Int64}:
 -2  -2  0   1
 -1   0  1  -2
  2   2  0  -1
  0   2  0   2

In [42]:
C = zeros(Int, 4,4)
for i=1:4
  for j=1:4
    C[i,j] = round(Int, cofactor(A,i,j))
  end
end
C

4×4 Matrix{Int64}:
 -6  4  -14  -4
  0  0    0   0
 -6  4  -14  -4
  0  0    0   0

In [43]:
A = [3 3 -1; 2 1 -3; 0 2 5]

3×3 Matrix{Int64}:
 3  3  -1
 2  1  -3
 0  2   5

In [44]:
C = zeros(Int, 3,3)
for i=1:3
  for j=1:3
    C[i,j] = round(Int, cofactor(A,i,j))
  end
end
C

3×3 Matrix{Int64}:
  11  -10   4
 -17   15  -6
  -8    7  -3

In [45]:
A = [4 0 -1; 1 3 2; 0 3 5]
b = [0,3,14]

3-element Vector{Int64}:
  0
  3
 14

In [46]:
det(A)

33.0

In [51]:
A1 = copy(A); A1[:,1]=b; det(A1)

33.0

In [53]:
A2 = copy(A); A2[:,2]=b; det(A2)


-66.0

In [54]:
A3 = copy(A); A3[:,3]=b; det(A3)

132.0